In [27]:
import numpy as np

def sigmoid(x):
    return 1/ (1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

def mean_square_error_loss(y_true,y_pred):
  return np.mean((y_true - y_pred)**2) # Use subtraction for MSE

input = np.array([[0,0],[0,1],[1,0],[1,1]]) # Correct the input array format
output = np.array([[0],[1],[1],[0]]) # Correct the output array format

input_size = 2
hidden_size = 2
output_size = 1

weights_input_hidden = np.random.rand(input_size,hidden_size)
bias_hidden = np.random.rand(hidden_size)
weights_hidden_output = np.random.randn(hidden_size,output_size)
bias_output = np.random.rand(output_size)

learning_rate = 0.1
epochs = 20000

for epoch in range(epochs):
  hidden_input = np.dot(input,weights_input_hidden)+bias_hidden
  hidden_output = sigmoid(hidden_input)

  final_input = np.dot(hidden_output,weights_hidden_output)+bias_output
  final_output = sigmoid(final_input)

  loss = mean_square_error_loss(output,final_output)

  error_output = final_output - output # Fix variable name 'outputs'
  gradient_output = error_output*sigmoid_derivative(final_output)

  error_hidden = np.dot(gradient_output,weights_hidden_output.T)
  gradient_hidden = error_hidden*sigmoid_derivative(hidden_output)

  weights_hidden_output -= learning_rate*np.dot(hidden_output.T,gradient_output)
  bias_output -= learning_rate*np.sum(gradient_output,axis=0)
  weights_input_hidden -= learning_rate*np.dot(input.T,gradient_hidden)
  bias_hidden -= learning_rate*np.sum(gradient_hidden,axis=0)

  if (epoch + 1)%2000 == 0: # Correct indentation
    print(f"Epoch:{epoch + 1},loss:{loss:.6f}")

results = [] # Fix variable name 'result'
for input_pair in input: # Fix variable name 'inputs', iterate over 'input'
  hidden_input = np.dot(input_pair,weights_input_hidden)+bias_hidden
  hidden_output = sigmoid(hidden_input)
  final_input = np.dot(hidden_output,weights_hidden_output)+bias_output
  final_output = sigmoid(final_input)
  results.append((input_pair,np.round(final_output[0],2))) # Append a tuple
print(results)

Epoch:2000,loss:0.179780
Epoch:4000,loss:0.025656
Epoch:6000,loss:0.006857
Epoch:8000,loss:0.003678
Epoch:10000,loss:0.002464
Epoch:12000,loss:0.001836
Epoch:14000,loss:0.001456
Epoch:16000,loss:0.001203
Epoch:18000,loss:0.001023
Epoch:20000,loss:0.000889
[(array([0, 0]), np.float64(0.03)), (array([0, 1]), np.float64(0.97)), (array([1, 0]), np.float64(0.97)), (array([1, 1]), np.float64(0.03))]


In [31]:
import numpy as np

class NeuralNet(object):
    RNG = np.random.default_rng()

    def __init__(self, topology:list[int] = []):
        self.topology = topology
        self.weight_mats = []
        self._init_matrices()

    def _init_matrices(self):
        #-- set up matrices
        if len(self.topology) > 1:
            j = 1
            for i in range(len(self.topology)-1):
                num_rows = self.topology[i]
                num_cols = self.topology[j] # Dedent this line to align with num_rows
                mat = self.RNG.random(size=(num_rows, num_cols)) # Dedent to match the for loop level
                self.weight_mats.append(mat)
                j += 1

    # ... rest of the code ...

import numpy as np

class NeuralNet(object):
    RNG = np.random.default_rng()

    def __init__(self, topology: list[int] = []):
        self.topology = topology
        self.weight_mats = []
        self._init_matrices()

    def _init_matrices(self):
        if len(self.topology) > 1:
            j = 1
            for i in range(len(self.topology) - 1):
                num_rows = self.topology[i]
                num_cols = self.topology[j]
                mat = self.RNG.random(size=(num_rows, num_cols))
                self.weight_mats.append(mat)
                j += 1

# Create an instance of the NeuralNet class
nn = NeuralNet([2, 3, 1])

# Display the initialized weight matrices
for i, weights in enumerate(nn.weight_mats):
    print(f"Weight matrix {i+1}:")
    print(weights)


Weight matrix 1:
[[0.59547254 0.04492351 0.7603022 ]
 [0.27728983 0.0222163  0.40370252]]
Weight matrix 2:
[[0.31167435]
 [0.77696074]
 [0.18740206]]


In [34]:
import numpy as np

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mean_square_error_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)  # Mean Squared Error Loss

# Neural Network class definition
class NeuralNet(object):
    RNG = np.random.default_rng()

    def __init__(self, topology: list[int] = []):
        self.topology = topology
        self.weight_mats = []
        self.biases = []
        self._init_matrices()

    def _init_matrices(self):
        # Initialize weight matrices and biases for each layer connection
        if len(self.topology) > 1:
            for i in range(len(self.topology) - 1):
                num_rows = self.topology[i]
                num_cols = self.topology[i + 1]
                mat = self.RNG.random(size=(num_rows, num_cols))
                bias = self.RNG.random(size=(num_cols,))
                self.weight_mats.append(mat)
                self.biases.append(bias)

    def forward_pass(self, inputs):
        activations = inputs
        for weights, bias in zip(self.weight_mats, self.biases):
            activations = sigmoid(np.dot(activations, weights) + bias)
        return activations

    def train(self, inputs, outputs, learning_rate=0.1, epochs=20000):
        for epoch in range(epochs):
            # Forward pass
            hidden_input = np.dot(inputs, self.weight_mats[0]) + self.biases[0]
            hidden_output = sigmoid(hidden_input)

            final_input = np.dot(hidden_output, self.weight_mats[1]) + self.biases[1]
            final_output = sigmoid(final_input)

            # Compute loss
            loss = mean_square_error_loss(outputs, final_output)

            # Backpropagation
            error_output = final_output - outputs
            gradient_output = error_output * sigmoid_derivative(final_output)

            error_hidden = np.dot(gradient_output, self.weight_mats[1].T)
            gradient_hidden = error_hidden * sigmoid_derivative(hidden_output)

            # Update weights and biases
            self.weight_mats[1] -= learning_rate * np.dot(hidden_output.T, gradient_output)
            self.biases[1] -= learning_rate * np.sum(gradient_output, axis=0)

            self.weight_mats[0] -= learning_rate * np.dot(inputs.T, gradient_hidden)
            self.biases[0] -= learning_rate * np.sum(gradient_hidden, axis=0)

            # Print the loss every 2000 epochs
            if (epoch + 1) % 2000 == 0:
                print(f"Epoch: {epoch + 1}, Loss: {loss:.6f}")

    def print_weights(self):
        for i, weights in enumerate(self.weight_mats):
            print(f"Weight matrix {i + 1}:")
            print(weights)
        for i, bias in enumerate(self.biases):
            print(f"Bias {i + 1}:")
            print(bias)

# Create and train the neural network
nn = NeuralNet([2, 2, 1])  # 2 neurons in input, 2 in hidden, 1 in output

# Define input and output data for XOR
input_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
output_data = np.array([[0], [1], [1], [0]])

# Print initial weights and biases
print("Initial weights and biases:")
nn.print_weights()

# Train the neural network
nn.train(input_data, output_data, learning_rate=0.1, epochs=20000)

# Print final weights and biases after training
print("\nFinal weights and biases:")
nn.print_weights()

# Test the trained network on the XOR inputs
results = []
for input_pair in input_data:
    prediction = nn.forward_pass(input_pair)
    results.append((input_pair, np.round(prediction[0], 2)))

print("\nPredicted outputs for XOR inputs:")
print(results)


Initial weights and biases:
Weight matrix 1:
[[0.10600272 0.84346438]
 [0.72373789 0.5849808 ]]
Weight matrix 2:
[[0.81279157]
 [0.71880256]]
Bias 1:
[0.72824983 0.61388377]
Bias 2:
[0.51166429]
Epoch: 2000, Loss: 0.231420
Epoch: 4000, Loss: 0.141978
Epoch: 6000, Loss: 0.014081
Epoch: 8000, Loss: 0.005337
Epoch: 10000, Loss: 0.003155
Epoch: 12000, Loss: 0.002208
Epoch: 14000, Loss: 0.001686
Epoch: 16000, Loss: 0.001359
Epoch: 18000, Loss: 0.001135
Epoch: 20000, Loss: 0.000973

Final weights and biases:
Weight matrix 1:
[[4.13333613 6.17152128]
 [4.14711672 6.23622533]]
Weight matrix 2:
[[-9.24486744]
 [ 8.52667391]]
Bias 1:
[-6.35167332 -2.691138  ]
Bias 2:
[-3.88327035]

Predicted outputs for XOR inputs:
[(array([0, 0]), np.float64(0.03)), (array([0, 1]), np.float64(0.97)), (array([1, 0]), np.float64(0.97)), (array([1, 1]), np.float64(0.03))]


In [38]:
# Multiclass Classification

import numpy as np

x = np.array([0.8, 0.6, 0.7])
y = np.array([0, 1, 0])
w1 = np.array([[0.2, 0.4, 0.1],
              [0.5, 0.3, 0.2],
              [0.3, 0.7, 0.8]])
w2 = np.array([[0.6, 0.4, 0.5],
              [0.1, 0.2, 0.3],
              [0.3, 0.7, 0.2]])
b1 = np.array([0.1, 0.2, 0.3])
b2 = np.array([0.1, 0.2, 0.3])
print(f"\nOld weights (w1):\n{w1}")
print(f"\nOld biases (b1):\n{b1}")
print(f"\nOld weights (w2):\n{w2}")
print(f"\nold biases (b2):\n{b2}")

# alpha
learning_rate = 0.01
epochs = 10000

def relu(x):
  return np.maximum(0,x)

def relu_derivative(x):
  return 1*(x>0)

def softmax(A):
    exps = np.exp(A - np.max(A, axis=-1, keepdims=True))
    return exps / np.sum(exps, axis=-1, keepdims=True)

# Loss = summation(y_true * log(y_pred))
def lossFunction(y_true,y_pred):
  return -np.sum(y_true*np.log(y_pred))

for epoch in range(epochs):

  # Forward propagation

  # h1 = w1(x)+b1
  h1 = np.dot(x, w1)+b1
  # a1 = sig(h1)
  a1 = relu(h1)

  # h2 = w2(a1)+b2
  h2 = np.dot(a1, w2)+b2
  # a2 = softmax(h2)
  a2 = softmax(h2)

  # L = (h2-y)^2
  loss = lossFunction(y, a2)
  #error = a2 - y
  #Error = (a2 - y)
  error = a2 - y

print(error)
print(a2)
print(loss)



Old weights (w1):
[[0.2 0.4 0.1]
 [0.5 0.3 0.2]
 [0.3 0.7 0.8]]

Old biases (b1):
[0.1 0.2 0.3]

Old weights (w2):
[[0.6 0.4 0.5]
 [0.1 0.2 0.3]
 [0.3 0.7 0.2]]

old biases (b2):
[0.1 0.2 0.3]
[ 0.25502746 -0.58413061  0.32910315]
[0.25502746 0.41586939 0.32910315]
0.8773840448515435


In [19]:
  # d(L)/d(w2) = Error * a1
  d_L_d_w2 = error.dot(a1.T)

  # d(L)/d(b2) = Error
  d_L_d_b2 = np.mean(error, axis=0)

  d_L_d_hidden = np.dot(error, w2.T)
  d_hidden_d_input = relu_derivative(h1)

  # d(L)/d(w1) = Error * w2 * x
  d_L_d_w1 = np.dot(x.T, d_hidden_d_input * d_L_d_hidden)

  # d(L)/d(b1) = Error * w2
  d_L_d_b1 = np.mean(d_hidden_d_input * d_L_d_hidden, axis=0)


  # Update weights
  w2 -= learning_rate * d_L_d_w2
  b2 -= learning_rate * d_L_d_b2

  w1 -= learning_rate *d_L_d_w1
  b1 -= learning_rate * d_L_d_b1

  if (epoch + 1) % 1000 == 0:
    print(f"Epoch:{epoch + 1}, Loss: {loss:.4f}")


# Print final outputs
print("\nFinal outputs (a2):\n", a2)
print("Final Loss:\n", loss)

results = []
# for input_pair in inputs:
#           hidden_input = np.dot(input_pair, weights_input_hidden)+bias_hidden
#           hidden_output = sigmoid(hidden_input)
#           final_input = np.dot(hidden_output, weights_hidden_output)+bias_output
#           final_output = sigmoid(final_input)
#           results.append((input_pair,np.round(final_output[0],2)))
# print(results)

print(f"\nUpdated weights (w1):\n{w1}")
print(f"\nUpdated biases (b1):\n{b1}")
print(f"\nUpdated weights (w2):\n{w2}")
print(f"\nUpdated biases (b2):\n{b2}")
print(f"\nOutput (a2) after epoch {epoch + 1}:\n{a2}")


Epoch:10000, Loss: 0.8774

Final outputs (a2):
 [0.25502746 0.41586939 0.32910315]
Final Loss:
 0.8773840448515435

Updated weights (w1):
[[0.20115017 0.40115017 0.10115017]
 [0.50115017 0.30115017 0.20115017]
 [0.30115017 0.70115017 0.80115017]]

Updated biases (b1):
[0.10058413 0.20058413 0.30058413]

Updated weights (w2):
[[0.60149895 0.40149895 0.50149895]
 [0.10149895 0.20149895 0.30149895]
 [0.30149895 0.70149895 0.20149895]]

Updated biases (b2):
[0.1 0.2 0.3]

Output (a2) after epoch 10000:
[0.25502746 0.41586939 0.32910315]
